### ISSUE TITLE
Add the option to delete any section of the portfolio

### ISSUE THREAD

**Issue by deepak-2605** [swciitg/PortfolioBuilder#10]
Add the option to delete any section of the portfolio. For example, if a user doesn't have any experience, they may not want to include an experience section in their portfolio. Provide the option to remove a particular section. The code and preview should get updated accordingly. This option should be provided in front of every section. When selecting that option, that field in form should be disabled. Also, provide an option for the user to add that section again. When selecting the option to add a section, that field should be enabled again, and the code and preview parts should also be updated accordingly.

**NOTE: Do write comments in your code and write the code in separate files and import those files in the main page. Give meaningful names to files and variables .
Kindly avoid the authentication for now. Directly go to http://localhost:3000/portfolio**

**Comment by Tushar98644** [comment]
Kindly assign this issue to me

**Comment by deepak-2605** [comment]
@Tushar98644  Assigned to you

**Comment by Dhruv127** [comment]
please see PR #13 , do tell if need to add option to delete more sections also

**Comment by deepak-2605** [comment]
@Dhruv127, we appreciate your interest in contributing. However, please be informed that this particular issue has already been assigned to @Tushar98644. Therefore, we are unable to consider your pull request for this issue at this time. We encourage you to explore our other issues. Thank you for your understanding and willingness to contribute!

**Comment by deepak-2605** [comment]
@Tushar98644 Try to complete this by Thursday EOD.

**Comment by Ayush-Singh77** [comment]
hey  could you please assign me this task as i also want to contribute to it.

**Comment by prakharbhardwaj1504** [comment]
I will deliver it up to your expectation, kindly assign...

**Comment by Dhruv127** [comment]
Can you merge PR#13 now ?
Bro i have also given some time on it, do tell if i need to improve something on it.. will do it.

**Comment by AnkitGurwan** [comment]
@Tushar98644 we have de-assigned you. 

@Dhruv127 we are reviewing your PR now.

**Comment by Dhruv127** [comment]
please see PR #23
