### ISSUE TITLE
Change the name of sections

### ISSUE THREAD

**Issue by AnkitGurwan** [swciitg/PortfolioBuilder#11]
Give an option to user to rename sections i.e. Experience, Education, Skills to whatever he wants. For example : User can rename **Experience** section to **My Work**.

**NOTE: Do write comments in your code and write the code in separate files and import those files in the main page. Give meaningful names to files and variables .
Kindly avoid the authentication for now. Directly go to http://localhost:3000/portfolio**

**Comment by Tushar98644** [comment]
I would like to take up the issue

**Comment by AnkitGurwan** [comment]
Okay, assigning this to you.

**Comment by Dhruv127** [comment]
Please check PR #11

**Comment by AnkitGurwan** [comment]
For now, we are taking request on first come first basis. Issue was already assigned and he might be working on it.
@Tushar98644 please try to finish it by **Thursday Evening** so that others can get a chance if you are not able to do.

**Comment by Dhruv127** [comment]
Should priority be given to those who submitted their pull requests first, as seen in other well-maintained repositories? Or is it more reasonable for an individual to be assigned to numerous issues, necessitating a waiting period?

**Comment by Dhruv127** [comment]
Ok so the hack is...choose various issues from different repos, get you assigned and take your time to get the solution , so that other contributors get bored and leave . Ps no violation 🙂

**Comment by AnkitGurwan** [comment]
Firstly, we can't be unfair to someone to whom we have already assigned a task and accept someone else pull request.
Also there is no hack, if there are multiple requests for the same issue we give deadline to complete the task and consider other if assignee is not able to do on time.

**Comment by Dhruv127** [comment]
Most of the issues can be solved my many I belive , the main problem is with time . Moreover most of the good repos considered first PR request only or the one who first open the issue , as they don't have time to assign everyone . But ok , not all repos are good

**Comment by Dhruv127** [comment]
It's takes me time to complete it first.. so just I am saying . No issues but.

**Comment by Ayush-Singh77** [comment]
hey  could you please assign me this task as i also want to contribute to it.
