### ISSUE TITLE
Create Project Section

### ISSUE THREAD

**Issue by deepak-2605** [swciitg/PortfolioBuilder#17]
Provide an option to user to add Project Section. Allow users to input the project's name, description, image, tech stack, website link, GitHub link, project timeline, and indicate whether it was undertaken under the guidance of a professor or within a club or as a self-project. Ensure that if a user doesn't fill in any input field of the project, the UI should remain unaffected. Update the code and preview section accordingly.

**NOTE: Do write comments in your code and write the code in separate files and import those files in the main page. Give meaningful names to files and variables .
Kindly avoid the authentication for now. Directly go to http://localhost:3000/portfolio**

**Comment by Junaid-Mohamed** [comment]
Hi @deepak-2605 , I would like to work on this feature can you please assign it to me

**Comment by deepak-2605** [comment]
Assigning this to you @Junaid-Mohamed . Try to complete by Thursday EOD

**Comment by prakharbhardwaj1504** [comment]
I will deliver it up to your expectation, kindly assign...

**Comment by deepak-2605** [comment]
Assigned this to you @prakharbhardwaj1504

**Comment by Dhruv127** [comment]
Can you assign me now ?

**Comment by AnkitGurwan** [comment]
We have given enough time to individual assignees. 
@Dhruv127 we are assigning this to you now.

**Comment by Junaid-Mohamed** [comment]
The project is not sorted out, readme file is also not updated properly, hence not able to route through the project and do the necessary required fix or create a feature. @AnkitGurwan  @deepak-2605

**Comment by AnkitGurwan** [comment]
@Junaid-Mohamed Can you point out any particular issue in the readme/project? 
Many have already worked on it without any issue and we have also tried providing extra informations along with issues.

**Comment by Dhruv127** [comment]
PR #25

**Comment by Dhruv127** [comment]
please check updated changes

**Comment by AnkitGurwan** [comment]
@Dhruv127 reviewing your changes. Will update you by evening.
