### ISSUE TITLE
Make Card for successful entry of Sections

### ISSUE THREAD

**Issue by AnkitGurwan** [swciitg/PortfolioBuilder#19]
**Make a card for the successful entry of sections**: experience, education, awards, skills, etc. Currently, successful entry is just words/input written in a vertical order.
Make the width of experience, education and awards section same as the input sections but in case of skills try making small rounded (not fully) rectangles. Give proper border-radius and background shadow(if possible).

**NOTE: Do write comments in your code and write the code in separate files and import those files in the main page. Give meaningful names to files and variables .
Kindly avoid the authentication for now. Directly go to http://localhost:3000/portfolio**

**Comment by Utkarsh-ver** [comment]
can u assign this to me...I want to work on it

**Comment by AnkitGurwan** [comment]
@Utkarsh-ver do you have any idea for the design?

**Comment by HarshMakadiya** [comment]
@AnkitGurwan Hey there, Can I work on this issue?

**Comment by Maharsh04** [comment]
Hey !! Can I work on this issue?

**Comment by AnkitGurwan** [comment]
Guys, you can share your ideas (mainly about how you are going to place the input values in the card just a rough idea). 
Also tell if you can make the successful entry **editable**?

**Comment by HarshMakadiya** [comment]
I think a drop down model would work and upon click on edit the values will be filled we can make it editable and save it in our database.

**Comment by AnkitGurwan** [comment]
@HarshMakadiya What we are thinking for now is not to make request to backend and database for each input submission or a successful entry. Rather, we will give a save button for saving the progress which will go on to save the data in database.
**Can you save the successful entry on the client side and make it editable** using redux?

**Comment by AnkitGurwan** [comment]
@HarshMakadiya let me clarify more, you don't have to build the save functionality to save the data in database. You just have to implement redux and store the successful entries and show them as card below the input section and make that card editable.

**Comment by Shifat-Ali** [comment]
Hey @AnkitGurwan ,
I have already done this in PR #20  while creating dark theme.
Please look into my PR once.

**Comment by AnkitGurwan** [comment]
Yes, many have used it. I am assigning this to you.
If you face any difficulties you can contact me. Don't make it late than Saturday EOD.

**Comment by HarshMakadiya** [comment]
@AnkitGurwan thanks for assigning it to me. I will surely try to complete it by Saturday.

**Comment by HarshMakadiya** [comment]
![image](https://github.com/swciitg/PortfolioBuilder/assets/70363509/53378e4f-b2ea-4593-a965-e337143ccc95)

Hey, @AnkitGurwan can you please guide me on "Make a card for the successful entry of sections" like can you please explain where to put the card and how the card works ??.

**Comment by AnkitGurwan** [comment]
For i.e. if someone fill the education section then put the entries of education section in a card and place it directly below the education section. More and more card of education section can be place below it.
Similarly for other sections (experience, awards, interests, skills) .

Talking about how it works, you can give an update button or update icon on which if a user clicks user can update that particular card. Change the **update** icon to a **save** button after click. When user click on **save**, update the data in the redux.

**Comment by HarshMakadiya** [comment]
@AnkitGurwan Okay, for example in the below pic I have filled in the details, and it's directly below the education section now I have to make it in a card and also introduce an edit button to edit the card. Am I correct?
![image](https://github.com/swciitg/PortfolioBuilder/assets/70363509/faf4c9fc-f031-4161-a207-eb241e79210f)

**Comment by AnkitGurwan** [comment]
[Check it here](https://www.figma.com/file/E1imlqKRYF4NJ2FbayMdXR/Minimal-Login-Page-UI-Design-(Community)?type=design&node-id=0%3A1&mode=design&t=6oqs6YpykFD8QsDs-1)

Just created a very rough design for you for education section. Similarly you can do with other section.

**Comment by HarshMakadiya** [comment]
Understood, Thanks for replying.

**Comment by AnkitGurwan** [comment]
You can take some extra time if you wish 😊

**Comment by HarshMakadiya** [comment]
Hey, @AnkitGurwan, just a question upon click should I make a bootstrap model that popups and has value, and upon save it will save the data in redux?

**Comment by HarshMakadiya** [comment]
@AnkitGurwan 
![image](https://github.com/swciitg/PortfolioBuilder/assets/70363509/fec68224-b04a-475c-bfba-bc4af2ca197e)
![image](https://github.com/swciitg/PortfolioBuilder/assets/70363509/76b233d4-6202-436a-8bf2-0e82785a033c)
![image](https://github.com/swciitg/PortfolioBuilder/assets/70363509/c705c830-128e-4fba-896d-e04a322e64da)

you want something like this an i right?

**Comment by AnkitGurwan** [comment]
@HarshMakadiya exactly👍

**Comment by HarshMakadiya** [comment]
Also one more thing, should i implement delete button inside edit box on bottom right corner?

**Comment by AnkitGurwan** [comment]
Yes.
For skills only delete button will work (edit not required).

**Comment by HarshMakadiya** [comment]
![image](https://github.com/swciitg/PortfolioBuilder/assets/70363509/d78f60b3-7726-461a-af17-91f825ae1731)

would this style work for education?

**Comment by AnkitGurwan** [comment]
Can you make design similar to the design I provided? That has better readability rather than a normal vertical order of information.

**Comment by HarshMakadiya** [comment]
Sure I will try my best! What kind of design will appear upon edit icon click? can you please guide me on that?

**Comment by AnkitGurwan** [comment]
design will not change. Just the information on card will become editable.
In the design earlier shared, these are not values they are inputs. When we click on edit, value of these can be changed.
Hope, that helps.

**Comment by HarshMakadiya** [comment]
I got it! I will complete the education card and ping you here! Thanks for the clarification.

**Comment by HarshMakadiya** [comment]
![image](https://github.com/swciitg/PortfolioBuilder/assets/70363509/726ed086-5727-4a81-9827-4dfd1c8e430d)
@AnkitGurwan Can you please confirm this design? or should I change any thing?

**Comment by AnkitGurwan** [comment]
Yaa it looking good but don't omit any information like the name of college and add hyphen in date in your card.

**Comment by HarshMakadiya** [comment]
https://github.com/swciitg/PortfolioBuilder/pull/28#issue-1931714027 @AnkitGurwan Can you please check my pr?
