### ISSUE TITLE
Dark and Light Theme

### ISSUE THREAD

**Issue by deepak-2605** [swciitg/PortfolioBuilder#2]
Create a dark theme for the page (http://localhost:3000/portfolio). Use the button at top to toggle between light and dark themes.

**NOTE: Do write comments in your code and write the code in separate files and import those files in the main page. Give meaningful names to files and variables .
Kindly avoid the authentication for now. Directly go to http://localhost:3000/portfolio**

**Comment by Shifat-Ali** [comment]
Hey! I would like to work on this.

**Comment by deepak-2605** [comment]
@Shifat-Ali  You are assigned on this.

**Comment by amitkroutthedev** [comment]
I would happy to work on this.

**Comment by okprateek** [comment]
Hello, @deepak-2605 can you please assign me this issue ? I'm looking forward to work on this

**Comment by deepak-2605** [comment]
@okprateek  @amitkroutthedev  This issue has been assigned to @Shifat-Ali.
@Shifat-Ali Try to complete by Thursday EOD.
