### ISSUE TITLE
Minor Bugs

### ISSUE THREAD

**Issue by AnkitGurwan** [swciitg/PortfolioBuilder#24]
(For now, issue is only for beginners and the one's with no PR's till now😁)

Three bugs need to be fixed :
- Change text color of input fields of education, experience, awards, skills and interest section in **dark mode**.
- Make right half of the page ( http://localhost:3000/portfolio) fixed. Right part must have height equal to screen and should have different scroll from left part.
- Make download button look better ( you can use a download icon too).

**NOTE: Do write comments in your code and write the code in separate files and import those files in the main page. Give meaningful names to files and variables .
Kindly avoid the authentication for now. Directly go to http://localhost:3000/portfolio**

**Comment by bhavuk2002** [comment]
i am beginner but i have some PR merged. Can you assign me?

**Comment by AnkitGurwan** [comment]
@bhavuk2002 we will definately consider you if we do not find someone with no PR's.
We have created this issue with a purpose of helping new commers to start their open source journey.

**Comment by Himanshuch8055** [comment]
Can you assign it to me? Please

**Comment by ShrutiKolla** [comment]
@AnkitGurwan Can you please assign this to me?

**Comment by SajithMinrutha** [comment]
Can you assign it to me? Please

**Comment by AnkitGurwan** [comment]
Since it's a beginner's issue we will look for best PR solving our 3 bugs (only among the beginner's assigned).
bhanu we will also review your PR too.

**Comment by Dhruvrode** [comment]
Hi @AnkitGurwan  I would like to contribute. Can i know if the issue is still open!!

**Comment by ShrutiKolla** [comment]
@AnkitGurwan what all issues are closed?

**Comment by AnkitGurwan** [comment]
@ShrutiKolla have you installed all dependencies? 
 We are already working with it without any issue, can you tell specifically what is the issue?

**Comment by ShrutiKolla** [comment]
@AnkitGurwan yes i did npm i. It's showing 2 moderate and 6 high vulnerabilies. And they are not going away even after doing npm audiit fix --force

**Comment by AnkitGurwan** [comment]
are you able to start your server with 'npm start' ?

**Comment by alinasoy** [comment]
I am beginner and I have no PR. Can you assign me for this issue?
