### ISSUE TITLE
Create multiple layouts for Navbar Section of the portfolio

### ISSUE THREAD

**Issue by deepak-2605** [swciitg/PortfolioBuilder#3]
Create **atleast 3** designs for navbar of portfolio in preview. Store these designs in separate files in a single folder named **Navbar**.  Give an option to user to select which ever design user wants to keep. Try creating different designs (For eg :- fixed horizontal navbar, toggled navbar at left, etc.). Also update the Code Section according to the design selected by the User. 
**NOTE: Do write comments in your code and write the code in separate files and import those files in the main page. Give meaningful names to files and variables .
Kindly avoid the authentication for now. Directly go to http://localhost:3000/portfolio**

**Comment by gautam-bhagat** [comment]
Hii Deepak,
Kindly assign the issue to me! I'm handy with react and Tailwind. I might be able to solve the issue!

Thanks!

**Comment by deepak-2605** [comment]
@gautam-bhagat You are assigned on this.

**Comment by deepak-2605** [comment]
@gautam-bhagat  Could you please provide an update on the progress of this issue? How much work is left to be done?

**Comment by Dhruv127** [comment]
Assign me

**Comment by deepak-2605** [comment]
@Dhruv127 Assigned this to you.

**Comment by Dhruv127** [comment]
PR #27

**Comment by Dhruv127** [comment]
do check pr #35

**Comment by Dhruv127** [comment]
Please tell if I need to improve on something.

**Comment by shaurya-jain23** [comment]
I want to work on this, please assign it to me
