### ISSUE TITLE
Different Preview Screens

### ISSUE THREAD

**Issue by deepak-2605** [swciitg/PortfolioBuilder#30]
Provide an option to user  to preview their portfolio in three distinct modes: mobile view, tablet view, and large-screen view. When a user selects any of these modes, a preview will appear as a modal directly on the current page. You can enhance the user experience by providing icons as buttons for different viewing modes. 

**NOTE: Do write comments in your code and write the code in separate files and import those files in the main page. Give meaningful names to files and variables .
Kindly avoid the authentication for now. Directly go to http://localhost:3000/portfolio**

**Comment by shohan2001** [comment]
Can you assign this to me?

**Comment by deepak-2605** [comment]
@shohan2001 Assigned this to you.

**Comment by shohan2001** [comment]
@deepak-2605 please check the pr

**Comment by shaurya-jain23** [comment]
can you assign it to me
