### ISSUE TITLE
Create design for Intro section of portfolio

### ISSUE THREAD

**Issue by AnkitGurwan** [swciitg/PortfolioBuilder#32]
Create 2 designs for the introduction section in the portfolio : 
1. [Design 1](https://ucarecdn.com/84741a1c-dce3-483e-b9d4-00e6cb14d1b1/-/resize/1800x//-/format/auto/-/quality/smart/-/preview/) 
2. [Design 2](https://www.theme-junkie.com/wp-content/uploads/Ober-wp-theme.jpg)

**For now kindly use any random image for creating design. Don't use the image URL given by user.**

You not have to exactly copy the design. Try to replicate as much as possible and make sure to make the design responsive to different screen sizes.
Also, make sure to keep the colors according to theme color selected by the user and to make the design consistent if user doesn't provide any input value.

**Make use of inputs-Full name, About you, Where are you?, Phone Number, Email, Social media handles.**

**NOTE: Do write comments in your code and write the code in separate files and import those files in the main page. Give meaningful names to files and variables .
Kindly avoid the authentication for now. Directly go to http://localhost:3000/portfolio**

**Comment by swaleha2002** [comment]
Hi there!

I'd like to take on the task of designing the intro section for the portfolio. 
I believe a captivating intro section sets the tone for the entire portfolio and is crucial in creating a lasting first impression. Assigning me this task would allow me to contribute my design skills to enhance the visual appeal and user experience of the portfolio.

Looking forward to working on this!

**Comment by AnkitGurwan** [comment]
@swaleha2002 assigning this to you. 
Kindly ensure responsiveness of the design for different screen sizes and use the input suggested above.

**Comment by swaleha2002** [comment]
@AnkitGurwan yeah sure, Thank you!

**Comment by shaurya-jain23** [comment]
Can I work on this, please assign me this

**Comment by Virentanti** [comment]
I’d like to work on this. Please assign it to me.

**Comment by AnkitGurwan** [comment]
Assigned to all. One with early PR as well as good design, will be merged.
