### ISSUE TITLE
Create Design for Project Section

### ISSUE THREAD

**Issue by deepak-2605** [swciitg/PortfolioBuilder#33]
Create 2 designs for the project section of the  portfolio and provide an option to user to choose either of the design: 
1. [Design 1](https://lh6.googleusercontent.com/nw8OHK6cyi2vW0583fTC3_l5gpxxQH_5AuG-MGdQYJqp-LWoNBEXUlZjQ_oYXxYzSGOa29SCFO6LVECEv_UEyEx8XoC4LtfJ6o5cd9hC_eqdvReyk3Eh4ubJ5-FCSy5dyxqvVKvXEWvW45hRL8aq5xk=s320) 
2. In Design 2, align image and description in vertical manner and keep all other things similar to Design-1

You do not need to exactly copy the design. Try to replicate as much as possible and make sure to make the design responsive for different screen sizes. You can make changes in the design to cover all the input fields of the project section.
Also, make sure to keep the colors according to theme color selected by the user and to make the design consistent if user doesn't provide any input value. Also, make sure that if user doesn't provide  image for project, then also your design is consistent.

**NOTE: Do write comments in your code and write the code in separate files and import those files in the main page. Give meaningful names to files and variables .
Kindly avoid the authentication for now. Directly go to http://localhost:3000/portfolio**

**Comment by haxybaxy** [comment]
Can I do this?

**Comment by AnkitGurwan** [comment]
Yes. Give an option, near the input section of project, to user to keep the design user wants(vertical one or horizontal one).

Don't change the design of input section of projects, someone is already working on it. Just add an option to choose among two.

**Comment by Dhruv127** [comment]
PR #38

**Comment by shaurya-jain23** [comment]
Can you please assign it to me if it is not completed
