### ISSUE TITLE
Create design for award and interest section of portfolio

### ISSUE THREAD

**Issue by AnkitGurwan** [swciitg/PortfolioBuilder#34]
Re-design award and interest sections of the portfolio. Make it attractive and screen responsive.

**NOTE: Do write comments in your code and write the code in separate files and import those files in the main page. Give meaningful names to files and variables .
Kindly avoid the authentication for now. Directly go to http://localhost:3000/portfolio**

**Comment by Dhruv127** [comment]
assign me

**Comment by deepak-2605** [comment]
@Dhruv127 Assigning this to you. Can you share your idea or your designing regarding these sections?

**Comment by Dhruv127** [comment]
![Screenshot (206)](https://github.com/swciitg/PortfolioBuilder/assets/92450489/c41f559a-22a6-4697-99ad-320a67fa7596)
Check.. if you like it. I also have added a little bounce effect on each hobby.

**Comment by deepak-2605** [comment]
This looks great !!

**Comment by Dhruv127** [comment]
for awards also,  will this work, or should try changing anything for that?

**Comment by shaurya-jain23** [comment]
Can you please assign it to me, if it is not completed

**Comment by Dhruv127** [comment]
> for awards also, will this work, or should try changing anything for that?

?

**Comment by Dhruv127** [comment]
pr #45

**Comment by Dhruv127** [comment]
Is this fine?
