### ISSUE TITLE
Login with Microsoft button not working.

### ISSUE THREAD

**Issue by DebidYadav** [swciitg/PortfolioBuilder#39]
When we click on Login With Microsoft button, it shows site can't be reached.
Browser: Chrome

**Comment by AnkitGurwan** [comment]
@DebidYadav do you know how to use msAuth and fetch details of user from Microsoft i.e college outlook id, college roll number, Name registered in institute.

**Comment by Dhruv127** [comment]
i could try on this.

**Comment by AnkitGurwan** [comment]
Can you share your approach for this

**Comment by Nikhil-IITG** [comment]
I have solved this issue. Please assign this to me

**Comment by Nikhil-IITG** [comment]
should I make a copy of .env as sample_env at the location it needs to have that file?
