### ISSUE TITLE
Create Multiple Layouts for Education Section of the portfolio

### ISSUE THREAD

**Issue by deepak-2605** [swciitg/PortfolioBuilder#4]
Create atleast 3 designs for education section of portfolio in preview. Store these designs in separate files in a single folder named **Education**. Give an option to user to select which ever design user wants to keep. Try creating different designs (For eg :- table,card, timeline of the education(You can checkout this link [here.](https://www.vecteezy.com/vector-art/104485-free-education-timeline-vector-background)). Also update the Code Section according to the design selected by the User. Firstly, cover the designs given in the examples, and then feel free to create more designs.

**NOTE: Do write comments in your code and write the code in separate files and import those files in the main page. Give meaningful names to files and variables .
Kindly avoid the authentication for now. Directly go to http://localhost:3000/portfolio**

**Comment by A-viralS** [comment]
Hey I would like to work on this issue! I am handy with the required stack.

**Comment by deepak-2605** [comment]
@A-viralS Can you share your progress on this issue?

**Comment by coldrohak** [comment]
I can work on this, can you assign it to me?

**Comment by deepak-2605** [comment]
@coldrohak Assigned this to you.

**Comment by deepak-2605** [comment]
@coldrohak  Can you please share your update regarding this issue?

**Comment by coldrohak** [comment]
I have built the designs just need to integrate them

**Comment by shaurya-jain23** [comment]
I would like to work on this, can you assign it to me

**Comment by coldrohak** [comment]
Will create a PR by night..

**Comment by deepak-2605** [comment]
@shaurya-jain23  Assigned this to you.
