### ISSUE TITLE
Phone number validation.

### ISSUE THREAD

**Issue by DebidYadav** [swciitg/PortfolioBuilder#40]
No validation check for phone number on http://localhost:3000/portfolio under phone number. 
Current result: able to enter characters and more than 10 digits.
Expected result: User can't enter character and more than 10 digits.

**Comment by Dhruv127** [comment]
assign me , will do by today itself.

**Comment by DebidYadav** [comment]
I am working on this.

**Comment by DebidYadav** [comment]
I am working on this.

**Comment by AnkitGurwan** [comment]
@DebidYadav  Will merge after previewing it completely.

**Comment by DebidYadav** [comment]
Is there something else I can work on?
