### ISSUE TITLE
Create Multiple Layouts for Experience Section of the portfolio

### ISSUE THREAD

**Issue by AnkitGurwan** [swciitg/PortfolioBuilder#5]
Create atleast 3 designs for experience section of portfolio in preview. Store these designs in separate files in a single folder named **Experience**. Give an option to user to select which ever design user wants to keep. Try creating different designs (For eg :- table, card, timeline of the experience (You can checkout this link [here](https://www.slidegeeks.com/pics/dgm/l/w/Work_Experience_Based_Timeline_Powerpoint_Presentation_Templates_1.jpg)). Also update the Code Section according to the design selected by the User. Firstly, cover the designs given in the examples, and then feel free to create more designs.

**NOTE: Do write comments in your code and write the code in separate files and import those files in the main page. Give meaningful names to files and variables .
Kindly avoid the authentication for now. Directly go to http://localhost:3000/portfolio**

**Comment by A-viralS** [comment]
Hey!! You can assign this issue to me. I am handy with required tech stack.

**Comment by deepak-2605** [comment]
@A-viralS  Can you share your progress on this issue?

**Comment by A-viralS** [comment]
2 different designs are made. Getting some error while fetching them from their respective files. working on it.

**Comment by coldrohak** [comment]
I can work on this, can you assign it to me?

**Comment by AnkitGurwan** [comment]
Okay

**Comment by deepak-2605** [comment]
@coldrohak Can you please share  your update regarding this issue?

**Comment by coldrohak** [comment]
Yeah, I have built the designs just need to integrate them

**Comment by shaurya-jain23** [comment]
Can I work on this, please assign it to me

**Comment by coldrohak** [comment]
Will create a PR by night..

**Comment by deepak-2605** [comment]
@shaurya-jain23 Assigned this to you.
