### ISSUE TITLE
Add design for experience section

### ISSUE THREAD

**Issue by Ashmit-Verma** [swciitg/PortfolioBuilder#55]
![Screenshot 2024-10-08 144309](https://github.com/user-attachments/assets/7721eef5-8404-4575-9cb6-c65053419445)
Create new design for the experience section of the portfolio and provide an option to user to choose either of the design:

You do not need to exactly copy the  design but you can take inspiration from it. Make sure to make the design responsive for different screen sizes. You can make changes in the design to cover all the input fields of the experience section.
Also, make sure to keep the colors according to theme color selected by the user and to make the design consistent if user doesn't provide any input value. 

NOTE: Do write comments in your code and write the code in separate files and import those files in the main page. Give meaningful names to files and variables .

**Comment by swarupn17** [comment]
Hey @Ashmit-Verma I can do this task please can you assign it to me.
Thanks !

**Comment by Ashmit-Verma** [comment]
@swarupn17 Assigning this to you.

**Comment by Ashmit-Verma** [comment]
Updates? @swarupn17

**Comment by bilalsadiq03** [comment]
Hi @Ashmit-Verma, Assign this task to me for Hacktoberfest2024.
Thanks!

**Comment by Ashmit-Verma** [comment]
@bilalsadiq03 assigned to you.

**Comment by bilalsadiq03** [comment]
@Ashmit-Verma working on it, will update it soon

**Comment by laladwesh** [comment]
hey @Ashmit-Verma can i work on this issue?

**Comment by Ashmit-Verma** [comment]
> hey @Ashmit-Verma can i work on this issue?

assigned to you @laladwesh
