### ISSUE TITLE
Add design for Experience section 2

### ISSUE THREAD

**Issue by Ashmit-Verma** [swciitg/PortfolioBuilder#56]
Create new design for the project section of the portfolio and provide an option to user to choose either of the design:

You do not need to exactly copy the design. Try to replicate as much as possible and make sure to make the design responsive for different screen sizes. You can make changes in the design to cover all the input fields of the experience 
![Screenshot 2024-10-08 144706](https://github.com/user-attachments/assets/629452ff-e218-4fa9-a838-f41029c8d111)
section.
Also, make sure to keep the colors according to theme color selected by the user and to make the design consistent if user doesn't provide any input value. 

NOTE: Do write comments in your code and write the code in separate files and import those files in the main page. Give meaningful names to files and variables .

**Comment by Snehalgupta-07** [comment]
Hi @Ashmit-Verma  i can do this task pls assign it to me

**Comment by jegamboafuentes** [comment]
Hey @Ashmit-Verma! 👋

I saw your awesome issue and thought I'd let you know about [Lightning Bounties](https://www.lightningbounties.com/)! 🚀 It's a super easy-to-use app where you can add a Bitcoin reward to this issue, encouraging devs to jump in and help you solve it.

Here’s a quick tutorial to get started: [Lightning Bounties Tutorial](https://docs.lightningbounties.com/docs/posting-a-bounty/create-a-github-issue-and-submit-a-new-reward). 💡 You can post your issue there, set up a bounty, and whoever cracks the code gets rewarded instantly in Bitcoin. 🔥

Let me know if you have any questions or need help setting it up!

Cheers! ⚡

**Comment by laladwesh** [comment]
hey @Ashmit-Verma can i take up on this issue?

**Comment by Ashmit-Verma** [comment]
> hey @Ashmit-Verma can i take up on this issue?

assigned to you @laladwesh
