### ISSUE TITLE
Add new design for Education section

### ISSUE THREAD

**Issue by Ashmit-Verma** [swciitg/PortfolioBuilder#57]
![Screenshot 2024-10-08 145134](https://github.com/user-attachments/assets/0562aaac-6bcc-4301-abc7-a47c1159b055)
Create new design for the Education section of the portfolio 

You do not need to exactly copy the design. Try to replicate as much as possible and make sure to make the design responsive for different screen sizes. You can make changes in the design to cover all the input fields of the Education section.
Also, make sure to keep the colors according to theme color selected by the user and to make the design consistent if user doesn't provide any input value. 

NOTE: Do write comments in your code and write the code in separate files and import those files in the main page. Give meaningful names to files and variables .

**Comment by Snehalgupta-07** [comment]
hi @Ashmit-Verma i can do this task pls assign it to me

**Comment by Ashmit-Verma** [comment]
@Snehalgupta-07 Assigning this to you.

**Comment by Ashmit-Verma** [comment]
Updates ? @Snehalgupta-07

**Comment by Snehalgupta-07** [comment]
> Updates ? @Snehalgupta-07 

Will do it by tomorrow

**Comment by Ashmit-Verma** [comment]
> > Updates ? @Snehalgupta-07
> 
> Will do it by tomorrow

Updates?

**Comment by Srayash** [comment]
hey @Ashmit-Verma can you assign this to me?

**Comment by Ashmit-Verma** [comment]
Assigned to you @Srayash

**Comment by Srayash** [comment]
> Assigned to you @Srayash

I've already submitted my PR for the issue.
kindly review and give feedback or merge.
Thank You!
