### ISSUE TITLE
Minor Frontend Changes

### ISSUE THREAD

**Issue by Ashmit-Verma** [swciitg/PortfolioBuilder#58]
![Screenshot 2024-10-08 145613](https://github.com/user-attachments/assets/0863e488-1c8a-4bd7-965c-65c8160a037a)
Make input fields responsive for smaller screens . Make it consistent with the design , you can make minor changes to the design .

**Comment by swarupn17** [comment]
Hello @Ashmit-Verma I can do this task. Please can you assign this task to me.
Thanks !

**Comment by RohanKrMahato** [comment]
@Ashmit-Verma 

I've fixed the issue related to [Issue #58](link-to-issue). Please take a look when you have a chance. I'll be happy if you can review and merge it.

Thanks!
