### ISSUE TITLE
Add Toast

### ISSUE THREAD

**Issue by AnkitGurwan** [swciitg/PortfolioBuilder#6]
Add toast to download, add and delete/remove button of the sections. 
Refer to : [React-toastify](https://www.npmjs.com/package/react-toastify)

**NOTE: Do write comments in your code and write the code in separate files and import those files in the main page. Give meaningful names to files and variables .
Kindly avoid the authentication for now. Directly go to http://localhost:3000/portfolio**

**Comment by dhaneshragu** [comment]
I want to work on this

**Comment by Shifat-Ali** [comment]
Hey! I would like to work on this.

**Comment by AnkitGurwan** [comment]
@dhaneshragu I am assigning this to you. Try to finish it by Wednesday evening.

**Comment by Ayush-Singh77** [comment]
hey  could you please assign me this task as i also want to contribute to it.

**Comment by AnkitGurwan** [comment]
@Ayush-Singh77 We have already received a pull request from the assignee dhanesh . Issue is almost solved, we are reviewing the code.
We would love to assign you other unsolved/unassigned issues if you want.
