### ISSUE TITLE
Give different colors to sections

### ISSUE THREAD

**Issue by AnkitGurwan** [swciitg/PortfolioBuilder#7]
Give different colors to the sections **borders** (filled sections with light-green color border, partially filled with yellow-color border and no-color/or leave it is for unfilled sections).

**NOTE: Do write comments in your code and write the code in separate files and import those files in the main page. Give meaningful names to files and variables .
Kindly avoid the authentication for now. Directly go to http://localhost:3000/portfolio**

**Comment by Samaresh-Das** [comment]
Hello, I would like to take on this issue. And wouldn't it be good if unfilled sections have red borders?

**Comment by AnkitGurwan** [comment]
@Samaresh-Das You can work on it. Unfilled sections are not mandatory so giving a red color is not a good choice.

**Comment by prakharbhardwaj1504** [comment]
I will deliver it up to your expectation, kindly assign...

**Comment by Samaresh-Das** [comment]
> @Samaresh-Das You can work on it. Unfilled sections are not mandatory so giving a red color is not a good choice.

I made the PR #22
