### ISSUE TITLE
Add custom skills options

### ISSUE THREAD

**Issue by AnkitGurwan** [swciitg/PortfolioBuilder#9]
Create a custom skills option out of which user can select multiple skills he/she want, **a kind of vertical scroll**. Common skills such as Problem-solving, C/C++, Python, React.js, etc could be added in the list. Try to add multiple domains skills such as Computer Science, Electrical Engineering, Mechanical modelling software, etc **atleast 20 skills**.
When a user select a particular skill, try to show them with an image in the preview as shown in image of the skill below.

**NOTE: Do write comments in your code and write the code in separate files and import those files in the main page. Give meaningful names to files and variables .
Kindly avoid the authentication for now. Directly go to http://localhost:3000/portfolio** 

<img width="754" alt="Skills" src="https://github.com/swciitg/PortfolioBuilder/assets/109846346/f1eac988-7529-4d53-87f9-b3511a8a888f">

**Comment by DHRUVKHANDELWAL00** [comment]
hey @AnkitGurwan , can i work on it?

**Comment by deepak-2605** [comment]
@DHRUVKHANDELWAL00  Assigned this to you.

**Comment by prakharbhardwaj1504** [comment]
I will deliver it up to your expectation, kindly assign...

**Comment by AnkitGurwan** [comment]
@DHRUVKHANDELWAL00 Try to complete it by EOD (6th oct).

**Comment by Dhruv127** [comment]
You can assign me if issue doesn't get resolved

**Comment by deepak-2605** [comment]
@Dhruv127 Ok , Assigning this to you.

**Comment by Dhruv127** [comment]
Can you provode the images of skills that has to be used?

**Comment by AnkitGurwan** [comment]
Kindly use standard images available over google, like this one.

![React-icon svg](https://github.com/swciitg/PortfolioBuilder/assets/109846346/0c3fdca6-bb17-457e-85b8-3691b2085e31)

**Comment by Dhruv127** [comment]
PR #29

**Comment by Dhruv127** [comment]
Please check again
